version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: sweetshop-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: sweetshop
    volumes:
      - mongodb_data:/data/db
      - ./server/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - sweetshop-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: sweetshop-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGO_URI: mongodb://admin:password@mongodb:27017/sweetshop?authSource=admin
      JWT_SECRET: your_jwt_secret_key_here_development
      ACCESS_TOKEN_EXPIRES_IN: 15m
      REFRESH_TOKEN_EXPIRES_IN: 7d
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - sweetshop-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: sweetshop-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:5000/api
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - sweetshop-network

volumes:
  mongodb_data:

networks:
  sweetshop-network:
    driver: bridge
